# Generated by Django 2.1.15 on 2021-06-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210628_0814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingregient',
            new_name='Ingredient',
        ),
    ]
